server:
  port: 8086
  forward-headers-strategy: framework

jwt:
  secret: MiAVzqUXy5Tfr1kVIGpPMiAVzqUXy5Tfr1kVIGpP
  expiration: 86400

spring:
  application:
    name: ticket-service

  cloud:
    discovery:
      enabled: true
    config:
      enabled: false

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    url: jdbc:postgresql://postgresql-fabricefanmoe.alwaysdata.net/fabricefanmoe_ticket
    username: fabricefanmoe_ticket
    password: Graven.2020


eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${DISCOVERY_SERVICE_URL:http://localhost:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include: '*'

springdoc:
  swagger-ui:
    path: '/swagger-ui.html'
